function initStruc(){
    return(
        {
            player:{
                startPosition:{
                    x:0,
                    z:0,
                    y:50,
                },
                height:180,
                moveSpeed:11,
                moveHeightRange:9,
                bumpR:120,
            },
            objectsList:[
        
            ]        
        }
    );
}
function initBasicGround(){
    for(let x=-10;x<10;x++){
        for(let z=-10;z<10;z++){
            objects.objectsList.push(
                {
                    name:"ground",
                    type:1,//1标准长方体
                    paraList:{//携带的参数列表
                        x:x/5,
                        z:z/5,
                    },
                    position:{
                        x:x*100,
                        z:z*100,
                        y:-50,
                    },
                    size:{
                        x:100,
                        z:100,
                        y:100,
                    },
                    strokeWeight:10,
                    stroke:null,
                    fill:[0],
                    change(t){
                        let zv=Math.sin(this.paraList.x*this.paraList.z+t/10);
                        this.stroke=[
                            zv*120+120,
                            120-zv*120,
                            zv*60+60,
                        ];
                        this.strokeWeight=(zv+1)*10;
                    },
                }
            )
        }
    }    
}
function initBasicWall(){
    let show=false;
    let wallHeight=800;

    let currentColor;
    let currentFill;
    if(show){
        currentColor=[255];
        currentFill=[0];
    }else{
        currentColor=null;
        currentFill=null;
    }
    
    objects.objectsList.push(
        {
            name:"wall1",
            type:1,//1标准长方体
            position:{//中心点位置
                x:-1000,
                z:0,
                y:wallHeight/2,
            },
            size:{
                x:97,
                z:2200,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
            bump:{//立方体碰撞盒
                size:{
                    x:90,
                    z:2200,
                    y:wallHeight,
                },
            }
        },
        {
            name:"wall2",
            type:1,//1标准长方体
            position:{//中心点位置
                x:900,
                z:0,
                y:wallHeight/2,
            },
            size:{
                x:97,
                z:2200,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
            bump:{//立方体碰撞盒
                size:{
                    x:90,
                    z:2200,
                    y:wallHeight,
                },
            }
        },
        {
            name:"wall3",
            type:1,//1标准长方体
            position:{//中心点位置
                x:0,
                z:-1000,
                y:wallHeight/2,
            },
            size:{
                x:2200,
                z:97,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
            bump:{//立方体碰撞盒
                size:{//中心点位置
                    x:2200,
                    z:97,
                    y:wallHeight,
                },
            }
        },
        {
            name:"wall4",
            type:1,//1标准长方体
            position:{//中心点位置
                x:0,
                z:900,
                y:wallHeight/2,
            },
            size:{
                x:2200,
                z:97,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
            bump:{//立方体碰撞盒
                size:{//中心点位置
                    x:2200,
                    z:97,
                    y:wallHeight,
                },
            }
        },
        //支柱
        {
            name:"z1",
            type:1,//1标准长方体
            position:{//中心点位置
                x:-1000,
                z:-1000,
                y:wallHeight/2,
            },
            size:{
                x:100,
                z:100,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentColor,
        },
        {
            name:"z2",
            type:1,//1标准长方体
            position:{//中心点位置
                x:900,
                z:-1000,
                y:wallHeight/2,
            },
            size:{
                x:100,
                z:100,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
        },
        {
            name:"z3",
            type:1,//1标准长方体
            position:{//中心点位置
                x:900,
                z:900,
                y:wallHeight/2,
            },
            size:{
                x:100,
                z:100,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
        },
        {
            name:"z4",
            type:1,//1标准长方体
            position:{//中心点位置
                x:-1000,
                z:900,
                y:wallHeight/2,
            },
            size:{
                x:100,
                z:100,
                y:wallHeight,
            },
            stroke:currentColor,
            fill:currentFill,
        }
    )
}
function initBasicCelling(){
    for(let x=-10;x<10;x++){
        for(let z=-10;z<10;z++){
            let zValue=Math.sin((x/3)*(x/3)+(z/3)*(z/3))+1;
            objects.objectsList.push(
                {
                    name:"sky",
                    type:1,//1标准长方体
                    paraList:{//携带的参数列表
                        x:x/5,
                        z:z/5,
                    },
                    position:{
                        x:x*100,
                        z:z*100,
                        y:1500-zValue*100,
                    },
                    size:{
                        x:100,
                        z:100,
                        y:zValue*200,
                    },
                    strokeWeight:10,
                    stroke:[zValue*60+60,60-zValue*120,100],
                    fill:[0],
                    change(t){
                        this.position.y=Math.sin(this.paraList.x*this.paraList.x+this.paraList.z*this.paraList.z+t/40)*150+1300;
                    },
                }
            )
        }
    }    
}
function initBasicDisplayScreen(name,position,heading,fuc){
    let size,displayCubeSize;
    if(heading==0){
        size={x:300,z:20,y:300};
        displayCubeSize={x:300,z:0,y:300};
    }else{
        size={x:20,z:300,y:300};
        displayCubeSize={x:0,z:300,y:300};
    }
    objects.objectsList.push(
        {
            name:name,
            type:11,//11展示屏
            position:position,
            size:size,
            displayCubeSize:displayCubeSize,
            fuc:fuc,
            stroke:[255,255,0],
            fill:null,
            bump:{
                size:size
            }
        }
    );
}
function initBasicDisplayBox(name,position,sizeRto,fuc){
    objects.objectsList.push(
        {
            name:name,
            type:21,//21展示柜
            position:position,
            size:{
                x:100*sizeRto.x,
                z:100*sizeRto.z,
                y:100,
            },
            containCubeSize:{//立体展柜特有
                x:100*sizeRto.x,
                z:100*sizeRto.z,
                y:100*sizeRto.y,
            },
            fuc:fuc,
            stroke:[255],
            fill:[0,200],
            bump:{
                size:{
                    x:100*sizeRto.x,
                    z:100*sizeRto.z,
                    y:100*sizeRto.y,
                }
            }
        },        
    );
}