var objects={
    player:{
        "startPosition":{
            "x":400,
            "z":400,
            "y":50
        },
        "height":180,
        "moveSpeed":10,
        "moveHeightRange":9,
        "bumpR":120
    },
    objectsList:[
        //球体实验
        {
            name:"ball1",
            type:2,//2标准球体
            position:{//中心点位置
                x:0,
                z:0,
                y:300,
            },
            rotation:{
                x:0,
                z:0,
                y:0,  
            },
            size:{
                r:100,
            },
            stroke:[255],
            fill:null,
            change(t){
                this.rotation.y+=0.008;
                this.position.y=Math.cos(t/16)*10+300;
            }
        },
        {
            name:"platform",
            type:1,//1标准长方体
            position:{//中心点位置
                x:0,
                z:0,
                y:80,
            },
            size:{
                x:100,
                z:100,
                y:100,
            },
            strokeWeight:3,
            stroke:[255],
            fill:null,
            bump:{//立方体碰撞盒
                size:{
                    x:100,
                    z:100,
                    y:100,
                },
            }
        },
        //圆锥实验
        {
            name:"cone",
            type:3,//3标准圆锥
            position:{//中心点位置
                x:-500,
                z:0,
                y:300,
            },
            size:{
                r:60,
                h:170,
            },
            stroke:[255,255,0],
            fill:null,
        },
        {
            name:"platform",
            type:1,//1标准长方体
            position:{//中心点位置
                x:-500,
                z:0,
                y:80,
            },
            size:{
                x:100,
                z:100,
                y:100,
            },
            strokeWeight:3,
            stroke:[255],
            fill:null,
            bump:{//立方体碰撞盒
                size:{
                    x:100,
                    z:100,
                    y:100,
                },
            }
        },
        //圆柱实验
        {
            name:"cld",
            type:4,//4标准圆柱
            position:{//中心点位置
                x:500,
                z:0,
                y:300,
            },
            size:{//物体大小
                r:60,
                h:193,
            },
            stroke:null,
            fill:[0,255,0,100],
            change(t){//改变物体的颜色位置旋转...
                this.position.y=Math.sin(t/20)*20+300;
            },
        },
        {
            name:"platform",
            type:1,//1标准长方体
            position:{
                x:500,
                z:0,
                y:80,
            },
            size:{
                x:100,
                z:100,
                y:100,
            },
            strokeWeight:3,
            stroke:[255],
            fill:null,
            bump:{//立方体碰撞盒
                size:{
                    x:100,
                    z:100,
                    y:100,
                },
            }
        },  
        //展示屏实验
        {
            name:"displayScreen1",
            type:11,//11展示屏
            position:{//中心点位置
                x:0,
                z:500,
                y:300,
            },
            size:{
                x:300,
                z:20,
                y:300,
            },
            displayCubeSize:{//平面展柜特有
                x:300,
                z:0,
                y:300,
            },
            fuc:new TdFunctionFlat(
                -2,2,40,
                -2,2,40,
                `sin(x*y+T)`,
                `
                noStroke();
                fill(0,map(z,-1,1,255,0),map(z,-1,1,0,255));
                rect(px,py,map(z,-1,1,0,20));`
            ),
            stroke:[200,255,0],
            fill:null,
            bump:{
                size:{
                    x:300,
                    z:100,
                    y:300,
               }
            }
        },
        //展示屏实验2
        {
            name:"displayScreen2",
            type:11,//11展示屏
            position:{//中心点位置
                x:0,
                z:-500,
                y:250,
            },
            rotation:{
                x:0,
                y:0,
                z:0,
            },
            size:{
                x:300,
                z:300,
                y:300,
            },
            displayCubeSize:{//平面展柜特有
                x:300,
                z:300,
                y:300,
            },
            fuc:new TdFunctionFlat(
                -2,2,20,
                -2,2,20,
                `sin(x*x+y*y-T)`,
                `
                fill(220,map(z,-1,1,255,0),map(z,-1,1,0,255));
                rect(px,py,map(z,-1,1,10,20));`
            ),
            stroke:[255],
            fill:null,
            change(t){
                this.rotation.y+=0.008;
                this.position.y=Math.sin(t/20)*10+250;
            },
        },
    ]
}

//生成地面
initBasicGround();
//生成天花板
initBasicCelling();
//生成周围的墙
initCalWall(2200,2000,2000,[100],[0]);
initCalWallBlocks(2200,2000,2000,[100],[255]);
initBasicDisplayScreen(
    "展示屏3",
    {x:-500,z:-500,y:300},
    {x:1,z:1,y:1},
    new TdFunctionFlat(
        {author:"vezzzing",date:"2022.1.6",name:"233"},
        -5,5,40,
        -5,5,40,
        `sin(sin(x)*cos(y)+T)`,
        `
        noStroke();
        fill(sin(z*10)*120+120,map(z,-1,1,255,0),map(z,-1,1,0,255));
        rect(px,py,map(z,-1,1,0,5));`
    )
);
initBasicDisplayBox(
    "展柜1",
    {x:-500,z:500,y:80},
    {x:1.5,z:1.5,y:4},
    new GlFunction(
        -5,5,10,
        -5,5,10,
        `sin(x*y-map(mouseY,0,height,0,10)-T/9)`,
        `
        strokeWeight(0.5);
        stroke(255);    
        fill(map(x,-5,5,0,255),map(y,5,-5,255,0),map(z,-1,1,0,255));
        translate(0,z*100,0);
        box(5,map(abs(z),1,0,0,100),5);`
    )
);
initBasicDisplayBox(
    "展柜2",
    {x:500,z:500,y:80},
    {x:1,z:1,y:1},
    new GlFunction(
        -2,2,20,
        -2,2,20,
        `sin(sin(x)*y-T)`,
        `
        noStroke();
        fill(map(x,-2,2,255,0),map(sin(z*1.2),-1,1,0,250),map(y,-2,2,255,0));
        rotateX(z);
        rotateY(y)
        rotateX(z)
        box(2);`
    )
);
initBasicDisplayBox(
    "展柜3",
    {x:500,z:-500,y:80},
    {x:1,z:1,y:1},
    new GlFunction(
        -2,2,20,
        -2,2,20,
        `sin(x*y-map(mouseX,0,width,0,30))`,
        `
        strokeWeight(0.5);
        stroke(255);    
        fill(map(z,-1,1,0,255),map(z,-1,1,255,0),255);
        box(map(z,-1,1,0,5));`
    )
);