var objects={
    player:{
        startPosition:{
            x:500,
            z:500,
            y:50,
        },
        height:180,
        moveSpeed:9,
        moveHeightRange:9,
        bumpR:170,
    },
    objectsList:[
        {
            name:"wall1",
            type:1,//1标准长方体
            position:{
                x:-200,
                z:0,
                y:350,
            },
            size:{
                x:110,
                z:510,
                y:700,
            },
            stroke:[255],
            fill:[100,100,200],
            bump:{//立方体碰撞盒
                size:{
                    x:110,
                    z:510,
                    y:500,
                },
            }
        },
        {
            name:"wall2",
            type:1,//1标准长方体
            position:{
                x:-200,
                z:1500,
                y:250,
            },
            size:{
                x:110,
                z:510,
                y:500,
            },
            stroke:[255],
            fill:[100,100,200],
            bump:{//立方体碰撞盒
                size:{
                    x:110,
                    z:510,
                    y:500,
                },
            }
        },
        {
            name:"wall3",
            type:1,//1标准长方体
            position:{
                x:1200,
                z:1500,
                y:750,
            },
            size:{
                x:90,
                z:90,
                y:1500,
            },
            stroke:[255],
            fill:[0,250,0,100],
            bump:{//立方体碰撞盒
                size:{
                    x:90,
                    z:90,
                    y:1500,
                },
            }
        },
    ]
}

//生成地面
for(let x=0;x<20;x++){
    for(let z=0;z<20;z++){
        let zValue=Math.sin((x/8)*(x/8)+(z/8)*(z/8))+1;
        objects.objectsList.push(
            {
                name:"ground",
                type:1,//1标准长方体
                position:{
                    x:x*100,
                    z:z*100,
                    y:-zValue*50,
                },
                size:{
                    x:90,
                    z:90,
                    y:zValue*100,
                },
                stroke:[255],
                fill:[zValue*60+60,125-zValue*120,100,200],
            }
        )
    }
}
//生成天花板
for(let x=0;x<20;x++){
    for(let z=0;z<20;z++){
        let zValue=Math.sin((x/8)*(x/8)+(z/8)*(z/8))+1;
        objects.objectsList.push(
            {
                name:"sky",
                type:1,//1标准长方体
                position:{
                    x:x*100,
                    z:z*100,
                    y:1500-zValue*50,
                },
                size:{
                    x:90,
                    z:90,
                    y:zValue*100,
                },
                stroke:[255],
                fill:[zValue*60+60,125-zValue*120,100,200],
            }
        )
    }
}

